#!/usr/bin/env bash
#
# Creates .env for a testnet deploy with no manual editing.
#
#   bash script/setup-env.sh
#
# Generates two fresh wallets locally, derives the model commit, and writes everything into
# .env. Nothing is sent anywhere. The only thing left to do afterwards is fund both
# addresses from the faucet.
#
# Fresh wallets are generated rather than reused on purpose: a key that has been pasted
# anywhere, or used for anything else, should never be a deployer key.

set -euo pipefail

ENV_FILE=".env"
MODEL_VERSION="aval-underwriter-v0.1.0"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
ok()   { printf "  \033[32mok\033[0m  %s\n" "$1"; }
die()  { printf "\n\033[31mFAILED\033[0m  %s\n\n" "$1" >&2; exit 1; }

command -v cast >/dev/null || die "cast not found. Install Foundry first."
[ -f .env.example ] || die "run this from the aval-protocol directory"

if [ -f "$ENV_FILE" ]; then
  BACKUP=".env.backup.$(date +%s)"
  cp "$ENV_FILE" "$BACKUP"
  ok "existing .env backed up to $BACKUP"
fi

bold "Generating two fresh wallets"

DEPLOYER_OUT="$(cast wallet new)"
DEPLOYER_ADDR="$(echo "$DEPLOYER_OUT" | awk '/Address/ {print $NF}')"
DEPLOYER_KEY="$(echo "$DEPLOYER_OUT" | awk '/Private key/ {print $NF}')"

UW_OUT="$(cast wallet new)"
UW_ADDR="$(echo "$UW_OUT" | awk '/Address/ {print $NF}')"
UW_KEY="$(echo "$UW_OUT" | awk '/Private key/ {print $NF}')"

[ -n "$DEPLOYER_ADDR" ] && [ -n "$DEPLOYER_KEY" ] || die "could not parse the generated deployer wallet"
[ -n "$UW_ADDR" ] && [ -n "$UW_KEY" ] || die "could not parse the generated underwriter wallet"

MODEL_COMMIT="$(cast keccak "$MODEL_VERSION")"
ok "model commit derived from \"$MODEL_VERSION\""

cat > "$ENV_FILE" <<EOF
# Generated by script/setup-env.sh. Contains private keys. Never commit or share this file.

# ---- deployment ----------------------------------------------------------
PRIVATE_KEY=$DEPLOYER_KEY
OWNER_ADDRESS=$DEPLOYER_ADDR
# Testnet: filled in automatically by deploy-testnet.sh.
# Mainnet: set to the real USDT, 0x1E4a5963aBFD975d8c9021ce480b42188849D41d
USDT_ADDRESS=0x
MIN_BOND=10000000000

# ---- chain ---------------------------------------------------------------
# Mainnet  chain 196   https://rpc.xlayer.tech
# Testnet  chain 1952  https://testrpc.xlayer.tech/terigon
# Chain 195 is the OLD deprecated testnet. Do not use it.
CHAIN_ID=1952
XLAYER_RPC_URL=https://rpc.xlayer.tech
XLAYER_TESTNET_RPC_URL=https://testrpc.xlayer.tech/terigon

# ---- filled in by deploy-testnet.sh --------------------------------------
DEAL_MANAGER_ADDRESS=0x
REGISTRY_ADDRESS=0x
REPUTATION_ADDRESS=0x
VAULT_ADDRESS=0x
ADAPTER_ADDRESS=0x
DEPLOY_BLOCK=0

# ---- underwriting agent --------------------------------------------------
UNDERWRITER_PRIVATE_KEY=$UW_KEY
MODEL_COMMIT=$MODEL_COMMIT

# Optional. Without it the qualitative stage skips and underwriting proceeds on the
# structural model alone, which is by design and not a failure.
GROQ_API_KEY=
LLM_MODEL=llama3-70b-8192

# ---- verification --------------------------------------------------------
OKLINK_API_KEY=
EOF

chmod 600 "$ENV_FILE"
ok "$ENV_FILE written and locked to your user only"

cat <<EOF

$(bold "Fund these two addresses")

  Deployer     $DEPLOYER_ADDR
  Underwriter  $UW_ADDR

  Faucet: https://web3.okx.com/xlayer/faucet
  Claim 0.2 OKB for EACH address. They must be funded separately.

$(bold "Then run")

  bash script/deploy-testnet.sh

The private keys are in .env on this machine only. Do not open it, print it, or paste it
anywhere. Nothing you need to share with anyone is inside that file.
EOF
