import type { Metadata } from "next";
import { Navigation } from "@/components/landing/navigation";
import { FooterSection } from "@/components/landing/footer-section";
import { Page, PageHeader, Section, Note } from "@/components/site/primitives";
import { NETWORK, STATUS } from "@/lib/facts";

export const metadata: Metadata = {
  title: "Terms of service",
  description: "The terms on which this software is offered. It is experimental and unaudited.",
};

/**
 * Written to describe what is actually true of this deployment rather than to copy standard
 * boilerplate. Every factual statement here is verifiable in the repository or onchain.
 */
export default function TermsPage() {
  return (
    <Page>
      <Navigation />

      <PageHeader
        title="Terms of service"
        lede="Plain terms for experimental software. Last updated 16 August 2026."
      />

      <Section>
        <div className="max-w-2xl mx-auto space-y-12">
          <Note tone="warn">
            <span className="text-foreground font-medium">Read this part if nothing else.</span> Aval
            is unaudited, experimental software running on {STATUS.deployedMainnet ? "a public blockchain" : `${NETWORK.name}, a test network`}.
            You may lose everything you put into it. Do not deposit money you cannot afford to lose.
          </Note>

          <section>
            <h2 className="font-display text-xl font-semibold mb-4">What this is</h2>
            <p className="text-muted-foreground leading-[1.8] mb-4">
              Aval Protocol is a set of smart contracts and an accompanying interface. The contracts
              run autonomously on a public blockchain. This website is a way of reading and
              interacting with them, and nothing more.
            </p>
            <p className="text-muted-foreground leading-[1.8]">
              We do not custody your funds, hold your keys, or execute transactions on your behalf.
              Every action you take is a transaction you sign from your own wallet.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-4">No warranty</h2>
            <p className="text-muted-foreground leading-[1.8] mb-4">
              The software is provided as is, without warranty of any kind. It has not been audited
              by a professional security firm. We have run static analysis and published our own
              review, and neither of those is a guarantee that the contracts are free of defects.
            </p>
            <p className="text-muted-foreground leading-[1.8]">
              Smart contracts can contain bugs. Bugs in contracts holding value can result in the
              permanent and irreversible loss of that value.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-4">Not financial advice</h2>
            <p className="text-muted-foreground leading-[1.8] mb-4">
              Nothing on this site is financial, investment, legal or tax advice. The risk scores
              produced by the underwriting model are opinions generated by software, not
              recommendations, and they carry no guarantee of accuracy.
            </p>
            <p className="text-muted-foreground leading-[1.8]">
              Any performance figures shown describe past behaviour of a model on historical or
              synthetic data. They do not predict future results.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-4">Your responsibility</h2>
            <p className="text-muted-foreground leading-[1.8] mb-4">
              You are responsible for your own wallet, keys and transactions, for understanding what
              a transaction does before signing it, and for complying with the laws that apply to
              you where you live.
            </p>
            <p className="text-muted-foreground leading-[1.8]">
              Access may be restricted in some jurisdictions. It is your responsibility to determine
              whether using this software is lawful for you.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-4">Limitation of liability</h2>
            <p className="text-muted-foreground leading-[1.8]">
              To the fullest extent permitted by law, the authors and contributors are not liable
              for any loss or damage arising from your use of this software, including loss of
              funds, loss of profits, or losses caused by defects in the contracts, failures of the
              underlying network, or errors in the underwriting model.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-4">Changes</h2>
            <p className="text-muted-foreground leading-[1.8]">
              These terms may change as the protocol develops. The deployed contracts, however,
              behave exactly as their published source says regardless of what any page here
              claims. When the two disagree, the contracts are what is true.
            </p>
          </section>
        </div>
      </Section>

      <FooterSection />
    </Page>
  );
}
